### ISSUE TITLE
Server time out too short; creates zombie scsynth

### ISSUE THREAD

**Issue by Nyrt** [josiah-wolf-oberholtzer/supriya#140]
When setting up Supriya on my personal computer, I found that 1 (second) was too short a time for the server to boot and connect:
**>>> server.boot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nathan/supriya/supriya/realtime/Server.py", line 567, in boot
    raise Exception('Timeout')
**
However, I discovered that when the server object times out after successfully starting scsynth and jack, but before they connect to the client, it results in a zombie scsynth and jack process which will cause subsequent attempts to start the server to fail. 

When I adjusted the timeout window to 10 (seconds), I was able to start the server normally only after killing the extra scsynth processes.

**Comment by josiah-wolf-oberholtzer** [comment]
Hey, nice catch. I've been meaning to harden how server booting handles various failure scenarios.

I'm developing this on OSX, and currently my only usage of Linux is testing `supriya` on Travis-CI. Could you confirm some Linux assumptions for me? If you're not already running a Jack server, does `scsynth` start a Jack server when it boots? If `scsynth` _does_ start a Jack server, is the `jackd` process (or whatever it's called on Linux) a children process of the `scsynth` process?

Basically, I need to understand what the appropriate way to clean up after a failed `supriya.Server` boot is: do I need to perform a `killall` on `scsynth`/`jackd` or can I just kill the `subprocess.Popen('scsynth ...etc...')` that my `supriya.Server` creates?

I've just made some changes to the boot process in 110c9b6d and 0df598d9 which raise specific exceptions when either a) another `scsynth` process is already bound to the IP/port you're trying to boot on or b) the `scsynth` process "times out" because it doesn't start providing information to parse within a reasonable timespan. I'm catching these exceptions in `Server.boot` and handling them, but the code at the moment doesn't actually handle the failure conditions properly (which you'll discover if you set the timeout back to 1s from the new 10s setting). If you have any suggestions on `Doing It Right`™, let me know. Currently traveling across country but will hopefully have some kind of working fix and test for these failure conditions within the next couple days.

**Comment by josiah-wolf-oberholtzer** [comment]
@Nyrt See https://github.com/josiah-wolf-oberholtzer/supriya/pull/141 and specifically the new test at https://github.com/josiah-wolf-oberholtzer/supriya/pull/141/files#diff-4c823117808972eb6e55b14759a8ab6b.

Tests are passing for me under OSX and Travis-CI. `scsynth` processes no longer appear to leak out of a failed boot. Let me know if you're able to confirm on Linux with the branch in #141.

**Comment by Nyrt** [comment]
That works for me!
